apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorturl
  template:
    metadata:
      labels:
        app: shorturl
    spec:
      containers:
        - name: shorturl
          image: udit027/shorturl:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8001

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
